version: "3"
services:
  mysql:
    ports:
      - 3308:3306
    image: mysql:5.7
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=db_user
      - PMA_PASSWORD=db_pass
